"""add payment_orders table

Revision ID: 3a8c256ce871
Revises: 62120740964e
Create Date: 2026-04-26 02:14:50.111258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8c256ce871'
down_revision: Union[str, Sequence[str], None] = '62120740964e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=True),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_status'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_id'))

    op.drop_table('payment_orders')
    # ### end Alembic commands ###
