"""add subscription columns to users

Revision ID: 62120740964e
Revises: 835e568a5ed7
Create Date: 2026-04-26 01:57:54.122007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62120740964e'
down_revision: Union[str, Sequence[str], None] = '835e568a5ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default lets existing rows backfill; we drop it after the column is committed
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=False, server_default='trial'))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))

    # Grant existing users a 7-day trial starting from their created_at.
    op.get_bind().execute(
        sa.text(
            "UPDATE users SET trial_ends_at = "
            "  CASE "
            "    WHEN created_at IS NULL THEN CURRENT_TIMESTAMP "
            "    ELSE datetime(created_at, '+7 days') "
            "  END "
            "WHERE trial_ends_at IS NULL"
        )
        if op.get_bind().dialect.name == 'sqlite'
        else sa.text(
            "UPDATE users SET trial_ends_at = COALESCE(created_at, CURRENT_TIMESTAMP) + INTERVAL '7 days' "
            "WHERE trial_ends_at IS NULL"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
