"""add user_api_keys table

Revision ID: 835e568a5ed7
Revises: 584ac0771d70
Create Date: 2026-04-26 01:51:40.394255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835e568a5ed7'
down_revision: Union[str, Sequence[str], None] = '584ac0771d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=512), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_api_keys_user_id'), ['user_id'], unique=False)

    # Backfill: copy each user's existing single key into the new table as the default.
    # Bind boolean as a parameter so SQLAlchemy renders it per-dialect (SQLite=1, PG=true).
    op.get_bind().execute(
        sa.text(
            """
            INSERT INTO user_api_keys (user_id, provider, api_key_encrypted, model, is_default)
            SELECT id,
                   COALESCE(NULLIF(ai_provider, ''), 'anthropic'),
                   ai_api_key_encrypted,
                   COALESCE(ai_model, ''),
                   :is_def
            FROM users
            WHERE ai_api_key_encrypted IS NOT NULL AND ai_api_key_encrypted != ''
            """
        ),
        {"is_def": True},
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_api_keys_id'))

    op.drop_table('user_api_keys')
    # ### end Alembic commands ###
