"""add notes and notebooks tables

Revision ID: 8eaba0fcc715
Revises: 3a8c256ce871
Create Date: 2026-04-26 15:01:45.723630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaba0fcc715'
down_revision: Union[str, Sequence[str], None] = '3a8c256ce871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notebooks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notebooks_user_id'), ['user_id'], unique=False)

    op.create_table('problem_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_problem_note')
    )
    with op.batch_alter_table('problem_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_notes_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_notes_user_id'), ['user_id'], unique=False)

    op.create_table('notebook_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('answer_code', sa.Text(), nullable=False),
    sa.Column('include_answer', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notebook_id', 'problem_id', name='uq_notebook_problem')
    )
    with op.batch_alter_table('notebook_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notebook_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notebook_items_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notebook_items_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_notebook_items_problem_id'), ['problem_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notebook_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notebook_items_problem_id'))
        batch_op.drop_index(batch_op.f('ix_notebook_items_position'))
        batch_op.drop_index(batch_op.f('ix_notebook_items_notebook_id'))
        batch_op.drop_index(batch_op.f('ix_notebook_items_id'))

    op.drop_table('notebook_items')
    with op.batch_alter_table('problem_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_problem_notes_problem_id'))
        batch_op.drop_index(batch_op.f('ix_problem_notes_id'))

    op.drop_table('problem_notes')
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notebooks_user_id'))
        batch_op.drop_index(batch_op.f('ix_notebooks_id'))

    op.drop_table('notebooks')
    # ### end Alembic commands ###
