"""drop billing tables and subscription columns

Revision ID: b0ab8f9d3cf6
Revises: 8eaba0fcc715
Create Date: 2026-04-27 00:56:04.369390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ab8f9d3cf6'
down_revision: Union[str, Sequence[str], None] = '8eaba0fcc715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_orders_id')
        batch_op.drop_index('ix_payment_orders_order_no')
        batch_op.drop_index('ix_payment_orders_status')
        batch_op.drop_index('ix_payment_orders_user_id')

    op.drop_table('payment_orders')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('plan')
        batch_op.drop_column('trial_ends_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_ends_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.VARCHAR(length=20), server_default=sa.text("'trial'"), nullable=False))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DATETIME(), nullable=True))

    op.create_table('payment_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_no', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=20), nullable=False),
    sa.Column('plan', sa.VARCHAR(length=50), nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('provider_order_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('qr_code_url', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.create_index('ix_payment_orders_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_payment_orders_status', ['status'], unique=False)
        batch_op.create_index('ix_payment_orders_order_no', ['order_no'], unique=1)
        batch_op.create_index('ix_payment_orders_id', ['id'], unique=False)

    # ### end Alembic commands ###
